### ISSUE TITLE
multiple zoom buttons appearing on firefox mobile

### ISSUE THREAD

**Issue by bricechilders** [OpenBeta/ocm#7]
Don't know if this is a known issue, and haven't tried to repro on desktop, but just something I noticed. Screencap [here](https://imgur.com/a/YyF9m), since github mobile apparently doesn't allow document uploads.

Also, hi Viet! We met in Potrero where you told me about this project. I was looking around for it online for a while, and then stumbled upon it when researching the MP API.

**Comment by vietnugent** [comment]
Glad you found the project!  It is indeed a bug. I'll fix it in this working branch: https://github.com/OpenBeta/ocm/tree/feature/workspace

**Comment by vietnugent** [comment]
Fixed in https://github.com/OpenBeta/ocm/pull/10
